COMMENT ON DATABASE "OHDSI"
    IS 'OHDSI WebAPI database';

GRANT ALL ON DATABASE "OHDSI" TO ohdsi_admin;

GRANT TEMPORARY ON DATABASE "OHDSI" TO ohdsi_app;

GRANT TEMPORARY, CONNECT ON DATABASE "OHDSI" TO PUBLIC;