
DROP SCHEMA IF EXISTS webapi;

CREATE SCHEMA IF NOT EXISTS webapi
    AUTHORIZATION ohdsi_admin;

COMMENT ON SCHEMA webapi
    IS 'Schema containing tables to support WebAPI functionality';

GRANT USAGE ON SCHEMA webapi TO PUBLIC;

GRANT ALL ON SCHEMA webapi TO ohdsi_admin;

GRANT ALL ON SCHEMA webapi TO ohdsi_admin_user;

GRANT USAGE ON SCHEMA webapi TO ohdsi_app;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA webapi
GRANT ALL ON TABLES TO ohdsi_admin_user;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA webapi
GRANT INSERT, SELECT, UPDATE, DELETE, REFERENCES, TRIGGER ON TABLES TO ohdsi_app;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA webapi
GRANT USAGE, SELECT ON SEQUENCES TO ohdsi_app;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA webapi
GRANT EXECUTE ON FUNCTIONS TO ohdsi_app;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA webapi
GRANT USAGE ON TYPES TO ohdsi_app;


