
DROP SCHEMA IF EXISTS webapi;

CREATE SCHEMA IF NOT EXISTS webapi
    AUTHORIZATION <ohdsiAdminUid>;

COMMENT ON SCHEMA webapi
    IS 'Schema containing tables to support WebAPI functionality';

GRANT USAGE ON SCHEMA webapi TO PUBLIC;

GRANT ALL ON SCHEMA webapi TO <ohdsiAdminUid>;

GRANT ALL ON SCHEMA webapi TO <ohdsiAdminUserUid>;

GRANT USAGE ON SCHEMA webapi TO <ohdsiAppUid>;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA webapi
GRANT ALL ON TABLES TO <ohdsiAdminUserUid>;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA webapi
GRANT INSERT, SELECT, UPDATE, DELETE, REFERENCES, TRIGGER ON TABLES TO <ohdsiAppUid>;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA webapi
GRANT USAGE, SELECT ON SEQUENCES TO <ohdsiAppUid>;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA webapi
GRANT EXECUTE ON FUNCTIONS TO <ohdsiAppUid>;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA webapi
GRANT USAGE ON TYPES TO <ohdsiAppUid>;


